src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Forecast_Start_Date__c</fullName>
        <label>Forecast Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is to determine what type of contact it is, is this contact point for delivery related queries or is this contact point for sales related queries and so.</description>
        <inlineHelpText>To determine what type of contact it is.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deliveries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notifier</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderFormControllerTest.cls
@isTest
public class OrderFormControllerTest{
    
    public static testMethod void testOrderFormController() {
        LIST<RecordType> RT=[Select Id from RecordType where SobjectType='Order'];
        Account tst=new Account(Name='Test Account', Forecast_Start_Date__c=system.today());
        insert tst;
        ID accId=tst.Id;
            
        Contact cont = new Contact( lastname='Testing Last Name' , type__c='Notifier', accountId=accId);  
        insert cont;
     
        Order Order_rec = new Order(
            RecordTypeId=RT[2].Id,
            AccountId=tst.Id,
            EffectiveDate=system.today()
            //Status='Draft'            
        );
        PageReference pageRef = Page.OrderForm;
        pageRef.getParameters().put('RecordType',RT[2].Id);
        Test.setCurrentPage(pageRef);
            
        ApexPages.StandardController sc = new ApexPages.StandardController(Order_rec);
        OrderFormController testPlan = new OrderFormController(sc);   
        
        DeliverySchedulerComponentController deliveryScheduleController = new DeliverySchedulerComponentController();
        testPlan.childComponentController = deliveryScheduleController;
        DeliveryScheduleWrapper wrapper = deliveryScheduleController.wrapper;
        PageReference pageReferenceBeforeSave = Apexpages.currentPage();     
        PageReference testPlanPageSaveReference =   testPlan.recsave();
        String orderId = testPlan.Order_rec.id;
        
        if(testPlanPageSaveReference!=null)     
        {   
            String pg=testPlanPageSaveReference.getURL();
            PageReference pgRf = new PageReference('/' + orderId);
            String pg1=pgRf.getUrl();
            String OrderIdFromPg1 = pg1.substring(0, pg1.length()-3);
            System.assertEquals(pg,OrderIdFromPg1);
        }
        else 
        {    
             System.assertEquals(ApexPages.currentPage().getUrl(),pageReferenceBeforeSave.getUrl());
        
        }
        
    }
   
}