src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Forecast_Start_Date__c</fullName>
        <label>Forecast Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Delivery_Schedule__c.object
<CustomObject>
    <description>A monthly delivery schedule for Communication hubs. The schedule consists of a number of consignments</description>
    <label>Delivery Schedule</label>
    <nameField>
        <label>Delivery Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DeliveryScheduleExtensionTest.cls
@isTest
public class DeliveryScheduleExtensionTest {
    static testMethod void testThatADeliveryScheduleIsCreatedWhenSaveIsPressed(){
        Date now = System.today();
        Delivery_Schedule__c deliverySchedule = new Delivery_Schedule__c(); 
        Account testAccount = new Account(name='Bob\'s Energy Supplier', Forecast_Start_Date__c=now);
        insert testAccount;
        Region__c region = new Region__c(name='God\'s Land');
        insert region;
        
        deliverySchedule.account__c = testAccount.id;
        deliverySchedule.region__c = region.id;
        deliverySchedule.month__c = 'January';
        deliverySchedule.year__c = '2015';

        ApexPages.StandardController controller = new ApexPages.StandardController(deliverySchedule);
        DeliveryScheduleExtension extension = new DeliveryScheduleExtension(controller);
        extension.save();
        
        Delivery_Schedule__c result = [SELECT account__c, region__c FROM Delivery_Schedule__c WHERE month__c = 'January' AND year__c = '2015'];
        System.debug(result.account__c);
        System.debug(result.region__c);
        System.assertEquals(testAccount.id, result.account__c);
        System.assertEquals(region.id, result.region__c);
    }
}