src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Forecast_Start_Date__c</fullName>
        <label>Forecast Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Consignment__c.object
<CustomObject>
    <description>An actual delivery of hub to an energy supplier</description>
    <label>Consignment</label>
    <nameField>
        <label>Consignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ConsignmentItem__c.object
<CustomObject>
    <fields>
        <fullName>Consignment__c</fullName>
        <label>Consignment</label>
        <referenceTo>Consignment__c</referenceTo>
        <relationshipLabel>Consignment Items</relationshipLabel>
        <relationshipName>Consignment_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Consignment Items</relationshipLabel>
        <relationshipName>Consignment_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>9</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Consignment Item</label>
    <nameField>
        <label>ConsignmentItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consignment Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Delivery_Schedule__c.object
<CustomObject>
    <description>A monthly delivery schedule for Communication hubs. The schedule consists of a number of consignments</description>
    <label>Delivery Schedule</label>
    <nameField>
        <label>Delivery Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DeliveryScheduleHelperTest.cls
@isTest
public class DeliveryScheduleHelperTest {
    static DeliveryScheduleHelper helper = new DeliveryScheduleHelper();
    
    static Account testAccount;
    static Region__c region;
    static Product2 product1;
    
    static DateHelper dateHelper = new DateHelper();
    static HubHelper hubHelper = new HubHelper();
    
    ////////////////////////////////////////////////////////////////////////////////
    // Setup methods
    public static Delivery_Schedule__c setupCreateHappyPath() {
        Date now = System.today();
        Delivery_Schedule__c deliverySchedule = new Delivery_Schedule__c(); 
        testAccount = new Account(name='Eon', Forecast_Start_Date__c=now);
        insert testAccount;
        region = new Region__c(name='South');
        insert region;
        product1 = new Product2(name='Hub', Family='Communications Hub');
        insert product1;
        
        deliverySchedule.account__c = testAccount.id;
        deliverySchedule.region__c = region.id;
        deliverySchedule.month__c = 'January';
        deliverySchedule.year__c = '2015';
        return deliverySchedule;
    }
    
    public static Delivery_Schedule__c setupSavedDeliverySchedule() {
        Delivery_Schedule__c deliverySchedule = setupCreateHappyPath();
        insert deliverySchedule;
        return deliverySchedule;
    }
    
    public static DeliveryScheduleWrapper setupDeliveryScheduleWrapper(Delivery_Schedule__c deliverySchedule) {
        DeliveryScheduleWrapper wrapper = new DeliveryScheduleWrapper();
        wrapper.deliverySchedule = deliverySchedule;
        wrapper.consignments = new List<Consignment__c>();
        for (Integer index = 1; index <=4; index++){        
            wrapper.consignments.add(createConsignment(index, wrapper));
        }
        return wrapper;
    }

    public static DeliveryScheduleWrapper setupSavedDeliveryScheduleWrapper(Delivery_Schedule__c deliverySchedule) {
        DeliveryScheduleWrapper wrapper = setupDeliveryScheduleWrapper(deliverySchedule);
        Integer count = 1;
        Integer hubTypes = hubHelper.hubTypeCount();
        for (Consignment__c consignment : wrapper.consignments) {
            consignment.Delivery_Schedule__c = wrapper.deliverySchedule.id;
            insert consignment;
            for (ConsignmentItem__c item : wrapper.items.get(count)) {
                item.Consignment__c = consignment.id;
                insert item;
            }
            count++;          
        }
        return wrapper;
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // Tests
    testMethod static void testCreate_DeliveryScheduleFieldsPopulated() {
        Delivery_Schedule__c  deliverySchedule = setupCreateHappyPath();
        
        DeliveryScheduleWrapper wrapper = helper.create(deliverySchedule);        
 
        System.assertEquals(testAccount.id, wrapper.deliverySchedule.account__c);
        System.assertEquals(region.id, wrapper.deliverySchedule.region__c);
    }
    
    testMethod static void testSave(){
        Delivery_Schedule__c  deliverySchedule = setupCreateHappyPath();
        DeliveryScheduleWrapper wrapper = setupDeliveryScheduleWrapper(deliverySchedule);
        Boolean result = helper.save(wrapper);
        System.assertEquals(true, result);
    }
    
    testMethod static void testLoad(){
        Delivery_Schedule__c  deliverySchedule = setupSavedDeliverySchedule();
        DeliveryScheduleWrapper wrapper = helper.load(deliverySchedule);
    }
    
    testMethod static void testAmend(){
        Delivery_Schedule__c  deliverySchedule = setupSavedDeliverySchedule();
        DeliveryScheduleWrapper wrapper = setupSavedDeliveryScheduleWrapper(deliverySchedule);
        Boolean result = helper.amend(wrapper);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // Helper methods
        static Consignment__c createConsignment(Integer index, DeliveryScheduleWrapper wrapper){
        Consignment__c consignment = new Consignment__c();
        consignment.Due__c = dateHelper.nextMonth().addDays((index -1) * 7);
        consignment.Position__c = index;
        consignment.Status__c = 'Created';
        List<Product2> products = hubHelper.hubTypes();
        List<ConsignmentItem__c> consignmentItems = new List<ConsignmentItem__c>();
        wrapper.items.put(index, consignmentItems);
        for (Product2 product : Products){
            ConsignmentItem__c item = new ConsignmentItem__c();
            item.Quantity__c = index * 100;
            item.Product__c = product.id;
            consignmentItems.add(item);
        }
        return consignment;
    } 
}