src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Energy_Supplier__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Energy Supplier</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Forecast_Start_Date__c</fullName>
        <label>Forecast Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is to determine what type of contact it is, is this contact point for delivery related queries or is this contact point for sales related queries and so.</description>
        <inlineHelpText>To determine what type of contact it is.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deliveries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notifier</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Energy_Supplier_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Energy_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to Account object of Energy Supplier</description>
        <label>Energy Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Energy Supplier Forecast</relationshipLabel>
        <relationshipName>Energy_Supplier_Forecast_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Energy Supplier Forecast</label>
    <nameField>
        <displayFormat>ESF-{00000}</displayFormat>
        <label>Energy Supplier Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energy Supplier Forecast</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NotificationForNoForecastTest.cls
/*
Once status field added to Energy Supplier Forecase asserts will be added to class to match the records the status updated and count emails being sent.
*/
@isTest
public class NotificationForNoForecastTest{
    
   static testMethod void test()    {
       Account[] al = new List<Account>();
       Contact[] c1 = new List<Contact>();
       for (Integer i=0;i<3;i++) {
           Account m = new Account(
               Name='Merchandise ' + i,
               Description='Some description',
           Forecast_Start_Date__c=Date.today()+30);
           al.add(m);
           Contact c = new Contact(LastName='graham',AccountId=m.id, Email='mailtosguptha@gmail.com', Type__c='Notifier');
           c1.add(c);
       }
       
       insert al;
       insert c1;
        NotificationForNoForecast bc = new NotificationForNoForecast();
        bc.query='select id,name from Account where id not in(select Energy_Supplier__c from Energy_Supplier_Forecast__c where CreatedDate = THIS_MONTH)';
        Test.startTest();
        Database.executeBatch(bc);
        Test.stopTest();
        }
        
}