src/objects/Aggregate_Order_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Aggregate Order Details</relationshipLabel>
        <relationshipName>Aggregate_Order_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>The number of the order that the account has placed</description>
        <label>Order Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Aggregate Order Details</relationshipLabel>
        <relationshipName>Aggregate_Order_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Aggregate Order Detail</label>
    <nameField>
        <label>Aggregate Order Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aggregate Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AggregateOrder__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Aggregate Orders</relationshipLabel>
        <relationshipName>Aggregate_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Aggregated Order</label>
    <nameField>
        <label>AggregateOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aggregated Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AggregateOrderWrapper.cls
public class AggregateOrderWrapper {
    public AggregateOrder__c order {get; set;}
    
    public Map<String,List<Aggregate_Order_Detail__c>> detailsByStatus {get;set;}

    public AggregateOrderWrapper() {
        order = new AggregateOrder__c();
        detailsByStatus = new Map<String,List<Aggregate_Order_Detail__c>>();
    }
    
    public List<Aggregate_Order_Detail__c> details() { 
    	List<Aggregate_Order_Detail__c> detailsList = new List<Aggregate_Order_Detail__c>();
    	for (List<Aggregate_Order_Detail__c> details: detailsByStatus.values()){
    		for (Aggregate_Order_Detail__c detail : details){
    			detailsList.add(detail);
    		}
    	}
    	return detailsList;
    }
    
    public List<Aggregate_Order_Detail__c> viewDetails() { 
    	List<Aggregate_Order_Detail__c> details = createViewDetails(detailsByStatus);
    	return details;
    }
    
    //////////////////////////////////////////////////////////////////////
    // Helper methods
    private List<Aggregate_Order_Detail__c> createViewDetails(Map<String, List<Aggregate_Order_Detail__c>> detailsByStatus) {
    	List<Aggregate_Order_Detail__c> viewDetails = new List<Aggregate_Order_Detail__c>();
        for (List<Aggregate_Order_Detail__c> detailList : detailsByStatus.values()){
            Aggregate_Order_Detail__c previousDetail = null;
            Aggregate_Order_Detail__c viewDetail = null;
            for (Aggregate_Order_Detail__c detail : detailList){
                viewDetail = detail.clone();
                hideDuplicateFields(viewDetail, previousDetail);
                viewDetails.add(viewDetail);
                previousDetail = detail;
            }
        }
    	return viewDetails;
    }
    
    private void hideDuplicateFields(Aggregate_Order_Detail__c detail, Aggregate_Order_Detail__c previousDetail) {
        if (previousDetail != null) {
            if (previousDetail.Account__c == detail.Account__c){
                detail.Account__c = null;
                if (previousDetail.Region__c == detail.Region__c){
                    detail.Region__c = null;
                    if (previousDetail.Order_Number__c == detail.Order_Number__c){
                        detail.Order_Number__c = null;
                    }
                }
            }
        }
    }
    
}