src/objects/Consignment__c.object
<CustomObject>
    <description>An actual delivery of hub to an energy supplier</description>
    <fields>
        <fullName>Delivery_Location__c</fullName>
        <label>Delivery Location</label>
        <referenceTo>Delivery_Location__c</referenceTo>
        <relationshipLabel>Consignments</relationshipLabel>
        <relationshipName>Consignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Consignment</label>
    <nameField>
        <label>Consignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ConsignmentItem__c.object
<CustomObject>
    <fields>
        <fullName>Consignment__c</fullName>
        <label>Consignment</label>
        <referenceTo>Consignment__c</referenceTo>
        <relationshipLabel>Consignment Items</relationshipLabel>
        <relationshipName>Consignment_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Consignment Items</relationshipLabel>
        <relationshipName>Consignment_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>9</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Consignment Item</label>
    <nameField>
        <label>ConsignmentItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consignment Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Delivery_Location__c.object
<CustomObject>
    <description>The location where a consignment will be delivered. There can be a maximum of two delivery locations per region per energy supplier</description>
    <label>Delivery Location</label>
    <nameField>
        <label>Delivery Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Delivery_Schedule__c.object
<CustomObject>
    <description>A monthly delivery schedule for Communication hubs. The schedule consists of a number of consignments</description>
    <label>Delivery Schedule</label>
    <nameField>
        <label>Delivery Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EditDeliveryScheduleExtensionTest.cls
@isTest
public class EditDeliveryScheduleExtensionTest {
    static DeliveryScheduleHelper helper = new DeliveryScheduleHelper();
    static HubHelper hubHelper = new HubHelper();
    
    testMethod static void testEditReturnsCorrectPageReference() {
        Delivery_Schedule__c deliverySchedule = DeliveryScheduleHelperTest.setupSavedDeliverySchedule();
        DeliveryScheduleWrapper wrapper = DeliveryScheduleHelperTest.setupSavedDeliveryScheduleWrapper(deliverySchedule);
        ApexPages.StandardController controller = new ApexPages.StandardController(deliverySchedule);
        EditDeliveryScheduleExtension extension = new EditDeliveryScheduleExtension(controller);
        PageReference result = extension.save();
        System.assertEquals('/a2/0', result.getUrl());
    }

    testMethod static void testEditChangesDatabase_ItemQuantity() {
        Delivery_Schedule__c deliverySchedule = DeliveryScheduleHelperTest.setupSavedDeliverySchedule();
        DeliveryScheduleHelperTest.setupSavedDeliveryScheduleWrapper(deliverySchedule);
        ApexPages.StandardController controller = new ApexPages.StandardController(deliverySchedule);
        EditDeliveryScheduleExtension extension = new EditDeliveryScheduleExtension(controller);
        DeliveryScheduleWrapper wrapper = extension.wrapper;
        List<ConsignmentItem__c> items = wrapper.items.get(1);
        Integer expected_item_quantity = 100000;
        for (ConsignmentItem__c item : items) {
            item.Quantity__c = expected_item_quantity;
        }
        PageReference result = extension.save();
        Consignment__c consignment = [
            SELECT id, name, Delivery_Location__c, Delivery_Schedule__c, Due__c, Instructions__c, Position__c, Status__c
            FROM Consignment__c 
            WHERE Delivery_Schedule__c = :deliverySchedule.id
            AND   Position__c = 1
        ];
        for (Product2 hub : hubHelper.hubTypes()) {
            ConsignmentItem__c item = [
                SELECT id,name,Consignment__c, Product__c, Quantity__c
                FROM ConsignmentItem__c
                WHERE
                    Consignment__c = :consignment.id
                    AND Product__c = :hub.id                
            ];
            System.assert(item != null);
            System.assert(item.quantity__c == expected_item_quantity);
        }
    }
    
    testMethod static void testEditChangesDatabase_ConsignmentDue() {
        Delivery_Schedule__c deliverySchedule = DeliveryScheduleHelperTest.setupSavedDeliverySchedule();
        DeliveryScheduleWrapper wrapper = DeliveryScheduleHelperTest.setupSavedDeliveryScheduleWrapper(deliverySchedule);
        
        // Change wrapper
        ApexPages.StandardController controller = new ApexPages.StandardController(deliverySchedule);
        EditDeliveryScheduleExtension extension = new EditDeliveryScheduleExtension(controller);
        PageReference result = extension.save();
    }
    
    testMethod static void testEditChangesDatabase_ConsignmentInstructions() {
        Delivery_Schedule__c deliverySchedule = DeliveryScheduleHelperTest.setupSavedDeliverySchedule();
        DeliveryScheduleWrapper wrapper = DeliveryScheduleHelperTest.setupSavedDeliveryScheduleWrapper(deliverySchedule);
        
        // Change wrapper
        ApexPages.StandardController controller = new ApexPages.StandardController(deliverySchedule);
        EditDeliveryScheduleExtension extension = new EditDeliveryScheduleExtension(controller);
        PageReference result = extension.save();
    }

}