src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is to determine what type of contact it is, is this contact point for delivery related queries or is this contact point for sales related queries and so.</description>
        <inlineHelpText>To determine what type of contact it is.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deliveries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notifier</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Forecast_Header__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Forecast_Header</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Forecast</label>
    <nameField>
        <displayFormat>SF-{00000000}</displayFormat>
        <label>Forecast</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NotificationForNoForecast.cls
global class NotificationForNoForecast implements Database.Batchable<sObject>{
   global String query;
    private List<Contact> contactList = new List<Contact>();
    EmailTemplate templateId = [Select id from EmailTemplate where name = 'NotifyDCCUserForNoForecast'];
    
   global Database.QueryLocator start(Database.BatchableContext BC)
   {
       System.debug('Apex job started');
       //Query results list of accounts who aren't yet submitted thier forecast for current month.
       query = 'select id,name from Account where id not in(select Account__c from Forecast_Header__c where CreatedDate = THIS_MONTH and Status__c!=\'Created\')'; 
      
       return Database.getQueryLocator(query); 
   }
  
   global void execute(Database.BatchableContext BC, List<Account> scope)
   {
       for(Account acc: scope) 
        {  
            System.debug('Job execute started for: '+acc);
            contactList = [select id, lastname, title from Contact where Accountid=:acc.id and Type__c='Notifier'];
             
            if(contactList.size()>0 && templateId!=null){
                try{ 
		                System.Debug('Mail Message to Contact'+contactList[0]);
		                AlertEmailUtility.sendEmailToContact(contactList[0], templateId.Id);
                }catch(EmailException em ){
                	System.debug('Mail sent failed for:'+ contactList[0].Title +' '+contactList[0].LastName);
                }
            }
        
         }
        System.debug('Apex job finished'); 
        
   }   
   global void finish(Database.BatchableContext BC) 
   {
       } 
}