src/objects/Energy_Supplier_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Current_Month_19__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 19</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_1__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_20__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 20</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_21__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 21</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_22__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 22</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_23__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 23</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_24__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 24</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_2__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_3__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_4__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_5__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 5</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_6__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 6</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_7__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 7</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_8__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 8</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Month_9__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Current_Month 9</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Energy_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to Account object of Energy Supplier</description>
        <label>Energy Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Energy Supplier Forecast</relationshipLabel>
        <relationshipName>Energy_Supplier_Forecast_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Forecast_Header__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Forecast Header</label>
        <referenceTo>Forecast_Header__c</referenceTo>
        <relationshipLabel>Energy Supplier Forecast</relationshipLabel>
        <relationshipName>Energy_Supplier_Forecast</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_10__c</fullName>
        <label>Month 10</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_11__c</fullName>
        <label>Month 11</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_12__c</fullName>
        <label>Month 12</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_13__c</fullName>
        <label>Month 13</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_14__c</fullName>
        <label>Month 14</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_15__c</fullName>
        <label>Month 15</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_16__c</fullName>
        <label>Month 16</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_17__c</fullName>
        <label>Month 17</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_18__c</fullName>
        <label>Month 18</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_19__c</fullName>
        <label>Month 19</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_1__c</fullName>
        <label>Month 1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_20__c</fullName>
        <label>Month 20</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_21__c</fullName>
        <label>Month 21</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_22__c</fullName>
        <label>Month 22</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_23__c</fullName>
        <label>Month 23</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_24__c</fullName>
        <label>Month 24</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_2__c</fullName>
        <label>Month 2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_3__c</fullName>
        <label>Month 3</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_4__c</fullName>
        <label>Month 4</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_5__c</fullName>
        <label>Month 5</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_6__c</fullName>
        <label>Month 6</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_7__c</fullName>
        <label>Month 7</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_8__c</fullName>
        <label>Month 8</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_9__c</fullName>
        <label>Month 9</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Month_10__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 10</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_11__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 11</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_12__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 12</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_13__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 13</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_14__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 14</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_15__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 15</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_16__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 16</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_17__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 17</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_18__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 18</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_19__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 19</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_1__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_20__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 20</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_21__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 21</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_22__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 22</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_23__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 23</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_24__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 24</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_2__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_3__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_4__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_5__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 5</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_6__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 6</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_7__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 7</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_8__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 8</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_9__c</fullName>
        <defaultValue>000</defaultValue>
        <label>Previous_Month 9</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;new&quot;</defaultValue>
        <label>Status</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Energy Supplier Forecast</label>
    <nameField>
        <displayFormat>ESF-{00000}</displayFormat>
        <label>Energy Supplier Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energy Supplier Forecast</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Forecast_Header__c.object
<CustomObject>
    <fields>
        <fullName>Forecast_Submitted_Month__c</fullName>
        <label>Forecast Submitted Month</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Forecast</label>
    <nameField>
        <displayFormat>SF-{00000000}</displayFormat>
        <label>Forecast</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EditEnergySupplierForecast.cls
public with sharing class EditEnergySupplierForecast 
{
 public List<Energy_Supplier_Forecast__c> supplierForecast {get;set;}
    public Id forecastId {get;set;}
    public Energy_Supplier_Forecast__c monthDisplay {get;set;}
    public Boolean submitted {get;set;}
    private Forecast_Header__c forecastHeader {get;set;}
    DateHelper dateHelper = new DateHelper();
    
    public PageReference Submit()
    {
        PageReference pageRef = new PageReference('/a0A/o');
        //submit logic here
        if(forecastHeader.Status__c == 'Created')
        {
            forecastHeader.Status__c = 'Submitted';
            forecastHeader.Forecast_Submitted_Month__c = dateHelper.nameOfMonth(System.today());
        }
        //additional checks?
        
        update forecastHeader;
        pageRef.setRedirect(True);
        return pageRef;
    }
    
    public PageReference Cancel()
    {
        PageReference pageRef = new PageReference('/a0A/o');
        pageRef.setRedirect(True);
        return pageRef;
    }
    
    public PageReference Save()
    {
        PageReference pageRef = new PageReference('/a0A/o');
        pageRef.setRedirect(True);
        //put some save stuff here
        update supplierForecast;
        return pageRef;
    }
    
    public Boolean getSubmitState()
    {
        If(forecastHeader.Status__c == 'Submitted')
        {
            submitted=true;
        }
        else
        {
        	submitted=false;
        }
        return submitted;	
    }
        
    public EditEnergySupplierForecast(ApexPages.StandardController controller)
    {
        
        forecastId = ApexPages.currentPage().getParameters().get('Id');
        
        // get the header status
        try
        {
        	forecastHeader = [SELECT Status__c
                              FROM Forecast_Header__c
                              WHERE id = :forecastId];
        }
        catch (QueryException e) 
        {
            //handle this here
        }
                                  
        try 
        { 
            supplierForecast = [SELECT e.Previous_Month_9__c, e.Previous_Month_8__c, e.Previous_Month_7__c, e.Previous_Month_6__c, 
                                       e.Previous_Month_5__c, e.Previous_Month_4__c, e.Previous_Month_3__c, e.Previous_Month_2__c, 
                                       e.Previous_Month_24__c, e.Previous_Month_23__c, e.Previous_Month_22__c, e.Previous_Month_21__c, 
                                       e.Previous_Month_20__c, e.Previous_Month_1__c, e.Previous_Month_19__c, e.Previous_Month_18__c, 
                                       e.Previous_Month_17__c, e.Previous_Month_16__c, e.Previous_Month_15__c, e.Previous_Month_14__c, 
                                       e.Previous_Month_13__c, e.Previous_Month_12__c, e.Previous_Month_11__c, e.Previous_Month_10__c, 
                                       e.Month_9__c, e.Month_8__c, e.Month_7__c, e.Month_6__c, e.Month_5__c, e.Month_4__c, e.Month_3__c, 
                                       e.Month_2__c, e.Month_24__c, e.Month_23__c, e.Month_22__c, e.Month_21__c, e.Month_20__c, 
                                       e.Month_1__c, e.Month_19__c, e.Month_18__c, e.Month_17__c, e.Month_16__c, e.Month_15__c, 
                                       e.Month_14__c, e.Month_13__c, e.Month_12__c, e.Month_11__c, e.Month_10__c, e.Forecast_Header__c, 
                                       e.Energy_Supplier__c, e.Current_Month_9__c, e.Current_Month_8__c, e.Current_Month_7__c, 
                                       e.Current_Month_6__c, e.Current_Month_5__c, e.Current_Month_4__c, e.Current_Month_3__c, 
                                       e.Current_Month_2__c, e.Current_Month_24__c, e.Current_Month_23__c, e.Current_Month_22__c, 
                                       e.Current_Month_21__c, e.Current_Month_20__c, e.Current_Month_1__c, e.Current_Month_19__c, 
                                       e.Current_Month_18__c, e.Current_Month_17__c, e.Current_Month_16__c, e.Current_Month_15__c, 
                                       e.Current_Month_14__c, e.Current_Month_13__c, e.Current_Month_12__c, e.Current_Month_11__c, 
                                       e.Current_Month_10__c, e.Comm_Hub_Variant__c 
                                 FROM Energy_Supplier_Forecast__c e
                                 WHERE e.Forecast_Header__c = :forecastId];
          
           getSubmitState();
           monthDisplay = supplierForecast.get(0);               
        }
        catch (QueryException e) 
        {
            //handle this here
        }
        
    }
}