src/objects/Forecast_Header__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Forecast_Header</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Forecast_Month__c</fullName>
        <label>Forecast Month</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Forecast</label>
    <nameField>
        <displayFormat>SF-{00000000}</displayFormat>
        <label>Forecast</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EnergySupplierForecastList.cls
Public class EnergySupplierForecastList 
{
    private Account accountToRestrict {get; set;}
    public String accountName {get; set;}
    public List<Forecast_Header__c> forecastHeader {get;set;}
    public Id forecastHeaderId {get; set;}
    
    public EnergySupplierForecastList (ApexPages.StandardController ctlr)
    {
        retrieveCurrentUserAccount();
        
        getForecastHeader();
        
    }
    
    public pageReference createNewForecast ()
    {
        PageReference pageRef = new PageReference('/apex/CreateForecast');
        
        return pageRef;
    }
    
    public pageReference view ()
    {
        PageReference pageRef = new PageReference('/apex/ViewForecast?id='+forecastHeaderId);
        
        return pageRef;
    }
    
    private void retrieveCurrentUserAccount ()
    {
        try 
        { 
            accountToRestrict = UserHelper.getAccountByName(UserHelper.getGroupName(UserHelper.getEnergySupplierGroupMembership()));  
            accountName = accountToRestrict.Name;
            system.debug('accountToRestrict = '+accountToRestrict);
        }
        catch (QueryException e) 
        {
            accountName = 'All Energy Supplier';
        } 
    }
    
    //public List<Forecast_Header__c> getForecastHeader ()
    public void getForecastHeader ()
    {
        try 
        { 
            if(accountToRestrict != null)
            {
                forecastHeader = [SELECT Name, Status__c, Forecast_Month__c, LastModifiedDate, Account__c
                                  FROM Forecast_Header__c
                                  WHERE Account__c = :accountToRestrict.Id];
            }
            else
            {
                // another query will bring back all supplier Forecasts
                forecastHeader = [SELECT Name, Status__c, Forecast_Month__c, LastModifiedDate, Account__c
                                  FROM Forecast_Header__c
                                  ];
            }
                                
            
        }
        catch (QueryException e) 
        {
            // now what?
        }
        
    }  
}